version: "2.4"
networks:
  dietmenu-dev:
    external: true
services:
  ui:
    image: nginx:latest
    ports:
      - "${PROXY_TCP_PORT:-30001}:80"
    networks:
      - dietmenu-dev
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html 
    restart: unless-stopped    